name: Update README activity
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: thedannicraft
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          OUTPUT_STYLE: HTML
          README_PATH: README.md
          COMMIT_MESSAGE: ⚡ Update README.md with latest activity
