name: Latest Blog Posts
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.thedannicraft.de/rss"
          commit_message: "⚡ Updated with the latest blog posts"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          committer_username: "github-actions[bot]"
          custom_tags: "postId/guid/"
          date_format: "mmm d, yyyy"
          template: '<tr><td><a href="$url"><img width="140px" src="https://n8n.thedannicraft.de/webhook/bb79c6e2-3bfb-44a3-a111-f983a4410487/grabPostImage/$postId"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr>$newline'
