name: Latest Blog Posts
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  update-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://blog.thedannicraft.de/rss"
          commit_message: "⚡ Updated with the latest blog posts"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          committer_username: "github-actions[bot]"
